sumfact.o : sumfact.c
	gcc -c sumfact.c

sumfact : sumfact.c
	gcc -o sumfact sumfact.c
.
launch.o : launch.c
	gcc -c launch.c

launch : launch.c
	gcc -o launch launch.c

clean:
	rm -f launch launch.o sumfact sumfact.o